---
abstract: 'Build and make available libffi'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Alien::Base: '0.022'
  Module::Build: '0.28'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  Alien::Base: '0.022'
  Module::Build: '0.28'
  perl: '5.006'
dynamic_config: '1'
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-FFI
requires:
  Alien::Base: '0.022'
  Alien::Base::ModuleBuild: '0.022'
  perl: '5.006'
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: https://github.com/plicease/Alien-FFI/issues
  homepage: http://perl.wdlabs.com/Alien-FFI
  repository: git://github.com/plicease/Alien-FFI.git
version: '0.14'
